"""изменил функцию даты

Revision ID: 2cf3d1b83a20
Revises: 615bf4cf04db
Create Date: 2024-12-19 10:48:26.819373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf3d1b83a20'
down_revision: Union[str, None] = '615bf4cf04db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_book', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               server_default=sa.text("(date('now'))"),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_book', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               server_default=sa.text('(curdate())'),
               existing_nullable=False)

    # ### end Alembic commands ###
