"""changed_edition

Revision ID: a01355507a7e
Revises: b372db1d83d9
Create Date: 2024-11-16 14:11:12.343410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a01355507a7e'
down_revision: Union[str, None] = 'b372db1d83d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instances_available', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edition', schema=None) as batch_op:
        batch_op.drop_column('instances_available')

    # ### end Alembic commands ###
